name: Docker Build

on:
  push:
    branches:
      - 'main'
      - '41-add-the-tests-around-parsing-messages-and-ensure-api-is-decent-to-work-with'

jobs:
  docker:
    runs-on: ubuntu-latest
    container: docker:dind
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/server.Dockerfile
          push: true
          tags: user/app:latest