name: Docker Build

on: push

jobs:
  docker_build:
    runs-on: ubuntu-latest
    container: "docker:dind"
    steps:
      - uses: actions/checkout@v3
      - name: docker-build
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME//\//_} # Replace slashes with underscores
          docker build -f docker/server.Dockerfile -t mmmtastymmm/bot-arena:$BRANCH_NAME --target=release .
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push mmmtastymmm/bot-arena:$BRANCH_NAME
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            docker tag mmmtastymmm/bot-arena:main mmmtastymmm/bot-arena:latest
            docker push mmmtastymmm/bot-arena:latest
          fi