name: Docker Build

on: push

jobs:
  docker_build:
    runs-on: ubuntu-latest
    container: "docker:dind"
    steps:
      - uses: actions/checkout@v2
      - name: docker-build
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME//\//_} # Replace slashes with underscores
          docker build -f docker/server.Dockerfile -t mmmtastymmm/bot-arena:latest --target=release .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push mmmtastymmm/bot-arena:latest