name: Docker Build

on:
  push:
    branches:
      - 'main'
      - '41-add-the-tests-around-parsing-messages-and-ensure-api-is-decent-to-work-with'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    container: "docker:dind"
    steps:
      - uses: actions/checkout@v2
      - name: docker-build
        run: |
          docker build -f docker/server.Dockerfile -t mmmtastymmm/bot-arena:latest --target=release .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push mmmtastymmm/bot-arena:latest